version: "3.7"
services:
  web:
    build: . # This tells Docker Compose to build an image using the Dockerfile in the current directory
    image: sodoo # Optionally specify a name for the built image
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  odoo-web-data:
  odoo-db-data:
